language: python
python:
- '3.6'
branches:
  only:
  - sources
env:
  global:
  - secure: QL7ERoqFpRBcM/sJZBXBLVqNXXlhpAWDM1Tmw+x7oD9rZbDPPeP4qBR/H+zb6PljnkTsoPRhd7DjirtxZXDBJEZ2ylekjq05MmiVsZLtOcqskR7Egk5NegAOBG5umFRZCweJC7WQkc6ynS4hTYs/kZoLKpuDLAuWSz4DL7Si8ydSiP7CHSRqQljnyGKfxDmK9PBrNbiIyI+onFz0XnrnMAQZIBuQ1p++/2WWdjZrVaW/KIBrDl9cpu5FR7tg43ygRmVbf5dkxKTH4CY3KmSPKApppcDQV/BhDv0p8+Sqxi9MwLjKjVg/CpVjznnlyWDLkCJD8GzjJtxmymiC0tznavo1GRhofP4XTPir9kV4tSCncYXDgsH42NqgLN+cxTEQZ160juCBKjU9ixD9wzzPwWj5P3U2nDmtFJx8aDnKO4AWOVzjT9TaW1+XOLpxVqokMc7aSunwCjzDK0Y8iWdDs6kFDYX7drSelqMpW5lvRyakxNM6wbrywFwmylwkH235qbQnv0L1jKnXgo8qpXjSIcPb3jLKmBGSYB1R9VGuTqoxDlvcWniqSC5d7ZwBaRrDZmH4IIZwU2IgQ1JCtM4+wSrTdHbsfrUgeKsDxHcws8OAxNTmUtSOKGOR6zAnFU/cHKA2tIMUTCwR9UD6dzVYyPEXWOa4qMrv12rLQLnonIc=
install: true
script:
- make publish
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: 'output'
  target_branch: master
  on:
    branch: sources
