language: python
python:
- '3.6'
branches:
  only:
  - sources
env:
  global:
    secure: ipjCQT5XOntCFX91qX0hNteA4d+CAihqGRe6GMKjqToOjaVoQJ86iEZLZF61vE90VngeaUeiIqpSRg2JySMJLzYhBCobqt3dLgQ1vk9+QpJ7AC9oiB5YkDm+TyWdoabb8zr7wFgjf4HxpeYc8nv5NNoRpvxzS1Rrry+O304HVu9kiESqnBKVF3DrYJa4fCem+oyqZW5ZbioYTP6Ie1MkFvCWDcTc1TRr+9BTw5QvyschISCPW5Q73io2tsjYMkEJF5bilqKfhaQ5HKe/Hl2msroT5NJJAmA0ppMRhtzYCKZjdRquGe9ATkabCMRHZ8SQFQ82X5+7C89Vlkn4NIxAiESBjX1G1DWDEirPS/5o8e6r2gGeFnUjiqZb0Q4J2AEfJyszbyGPahHUYpdctj+d/LJ6HGqZzk9FXPFxNECYFb9xT/BRawSn14MrC9eG12NzOX4IUB1pG6don1pTXU4QJESKYfVHWfFIXI8xq55ItywfpsYDvadEctIWofhpV6ZKiaFndEJqVFp1l0KX6OCq+FHsfsztLEkh5cRlH+KyInGjscGOFF+6YU1i+gQ/k7HYg1VR5wX46QP1ipgrjqHEiSLyO85IK4x/KTBRWso86/PFWlRRpu4aj5p48nSlXbHOT6x2eA8QXNclRVRGMZ0DI238yb6JKs9+2bUA3UO2zpY=
before_install:
- pip install pelican markdown ipython notebook
install: true
script:
- make publish
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  local_dir: output
  target_branch: master
  on:
    branch: sources
